# Generated by Django 4.0 on 2021-12-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libaray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TimeField(default='Default libaray')),
                ('serial', models.IntegerField(default=-1)),
            ],
        ),
    ]
